version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: flightfinder-postgres-dev
    environment:
      POSTGRES_DB: flightfinder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: